services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: metrics
      POSTGRES_USER: metrics
      POSTGRES_PASSWORD: metrics
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U metrics -d metrics"]
      interval: 5s
      timeout: 3s
      retries: 30

  web:
    build: .
    command: ["/app/entrypoint.sh","web"]
    ports: ["8000:8000"]
    environment:
      DJANGO_SECRET_KEY: dev
      DB_NAME: metrics
      DB_USER: metrics
      DB_PASSWORD: metrics
      DB_HOST: db
      DB_PORT: "5432"
      TZ: Europe/Warsaw
      GOOGLE_SERVICE_ACCOUNT_JSON: /secrets/runner.json
      GOOGLE_SHEETS_SPREADSHEET_ID: 
    volumes:
      - ./runner.json:/secrets/runner.json:ro
    depends_on:
      db: { condition: service_healthy }

  bot:
    build: .
    command: ["/app/entrypoint.sh","bot"]
    environment:
      DJANGO_SECRET_KEY: dev
      DB_NAME: metrics
      DB_USER: metrics
      DB_PASSWORD: metrics
      DB_HOST: db
      DB_PORT: "5432"
      DISCORD_TOKEN: 
      GUILD_ID: ""
      TZ: Europe/Warsaw
      GOOGLE_SERVICE_ACCOUNT_JSON: /secrets/runner.json
      GOOGLE_SHEETS_SPREADSHEET_ID: 
    volumes:
      - ./runner.json:/secrets/runner.json:ro
    depends_on:
      db: { condition: service_healthy }

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    environment:
      ACME_EMAIL: bytebrewmaster@gmail.com
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  dbdata:
  caddy_data:
  caddy_config: